name: checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python3 -m pip install ".[dev]"

      - name: Check style
        run: python3 -m ruff check . && ruff format --check .

  precommit_hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hook:
        - "end-of-file-fixer"
        - "trailing-whitespace"
        - "mixed-line-ending"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: ${{ matrix.hook }} --all-files
